config/routes.rb
CineJQM::Application.routes.draw do
  get "home/index"
  resources :tickets do
  get :autocomplete_ticket_category, :on=>:collection
  end
  resources :customers
  resources :ticketcounts do
  get :autocomplete_ticketcount_category, :on=>:collection
  end

   root :to => 'home#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
#has_many :tickets, :dependent => :destroy
has_many :tickets
#attr_accessible :tickets_attributes
#accepts_nested_attributes_for :tickets

def ticket_category
  ticket.category if ticket
 end

 def ticket_category=(category)
    self.ticket=Ticket.find_by_category(category) unless category.blank?
  
 end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
      format.js
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new
    @customer.tickets.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:id])
    @nooftickets = params[:customer][:no]+params[:slider]
    @customer.update_attributes(:name=>params[:customer][:name],:email=>params[:customer][:email],:phone=>params[:customer][:phone],:no=>@nooftickets,:ccn=>params[:customer][:ccn])
     
     @tickets = params[:customer][:no]+params[:slider]
     @length=@tickets.length
     @nos=Integer(@tickets[1..@length])
     @pos=@tickets[0]
     
     
     @i=1
      while @i<= @nos
      @customer.tickets.build
      @i=@i+1
      end  
      @tno=Integer(rand()*1000)
         respond_to do |format|
      if @customer.save
         @j=0
        @customer.tickets.each do |ticket|
          @tno=@tno+1
         
         if @pos =="B"
           @ticketcount=Ticketcount.find_by_category('Balcony')
           @count=Integer(@ticketcount.nooftickets)-1
           ticket.update_attributes(:cost=>'100',:category=>'Balcony',:tno=>@tno,:sno=>@tno)
           @ticketcount.update_attributes(:nooftickets=>@count)
          else if @pos == "F"
           @ticketcount=Ticketcount.find_by_category('First')
           @count=Integer(@ticketcount.nooftickets)-1
           ticket.update_attributes(:cost=>'100',:category=>'First',:tno=>@tno,:sno=>@tno)
           @ticketcount.update_attributes(:nooftickets=>@count)
          else 
           @ticketcount=Ticketcount.find_by_category('Second')
           @count=Integer(@ticketcount.nooftickets)-1
           ticket.update_attributes(:cost=>'25',:category=>'Second',:tno=>@tno,:sno=>@tno)
           @ticketcount.update_attributes(:nooftickets=>@count)
           end
         end
      end  

        format.html { redirect_to @customer, notice: 'Ticket was successfully booked.' }
        format.json { render json: @customer, status: :created, location: @customer }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
     @customer.tickets.each do |ticket|
       @category=ticket.category
        if @category=='Balcony'
         @ticketcount=Ticketcount.find_by_category('Balcony')
         @count=Integer(@ticketcount.nooftickets)+1
         @ticketcount.update_attributes(:nooftickets=>@count)
        else if @category=='First'
         @ticketcount=Ticketcount.find_by_category('First')
         @count=Integer(@ticketcount.nooftickets)+1
         @ticketcount.update_attributes(:nooftickets=>@count)
        else
         @ticketcount=Ticketcount.find_by_category('Second')
         @count=Integer(@ticketcount.nooftickets)+1
         @ticketcount.update_attributes(:nooftickets=>@count)
        
      end
     end
    end
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  def cancel
   
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer, :remote => true) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.fields_for :tickets do |fi| %>
     <%= render 'ticket_fields', :f => fi %>
    <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
    
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :ccn %><br />
    <%= f.text_field :ccn %>
  </div>
  <div class="field">
    <%= f.label :Type %><br />
    <%= f.text_field :no %>
    <label for="slider">No:</label>
    <input type="range" name="slider" id="slider" value="0" min="0" max="10" />
  </div>
    <div class="actions" >
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/_ticket_fields.html.erb
<div data-role="fieldcontain">
<%= f.autocomplete_field :ticket_category, autocomplete_ticketcount_category_ticketcounts_path,:update_elements => { :cost => "#ticket_cost", :nooftickets =>"#ticket_count"} ,:id => "ticket_category"%>
</br>
    <%= f.label :cost %><br />
    <%= f.text_field :ticket_cost, :id=> "ticket_cost" %><br />
    Tickets available:<br />
    <%= f.hidden_field :ticket_count,:id =>"ticket_count" %>
  
</div>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer. %></td>
    <td><%= customer. %></td>
    <td><%= customer. %></td>
    <td><%= customer. %></td>
    <td><%= customer. %></td>
    <td><%= customer. %></td>
    <td><%= customer. %></td>
    <td><%= customer. %></td>
    <td><%= link_to 'Show', customer %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy', customer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @customer.name %>
</p>

<p>
  <b>Email:</b>
  <%= @customer.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @customer.phone %>
</p>

<p>
  <b>CCN:</b>
  <%= @customer.ccn %>
</p>

<p>
  <b>No:</b>
  <%= @customer.no %>
</p>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>